# This is a workflow to rollback the website to a previous build if there's an issue with the current website.
# We bypass the build step here, and simply pick a previous website build to rollback to.
# See comment below on how to customize the date of the build to rollback to. Note that we only keep
# builds from the last 30 days.
name: Rollback Website
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
        # IMPORTANT: Customize the following to the date and workflow id of the website build that you want to rollback to
        # The format used for the date is YYYY-MM-DD
        # The current values are set to match the following workflow run: https://github.com/facebook/pyrefly/actions/runs/14781446659
          name: website-build-2025-05-01 # Update the date to the date of the build that you want to rollback to
          path: website/build
          run-id: 14781446659 # Update the workflow run ID to the one that you want to rollback to
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/build # The folder the action should deploy.
