# This is a workflow to rollback the website to a previous build if there's an issue with the current website.
# We bypass the build step here, and simply pick a previous website build to rollback to.
# Note that we only keep builds from the last 30 days.
name: Rollback Website
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      artifact_date:
        description: 'Date to rollback to (YYYY-MM-DD)'
        required: true
        type: string
      run_id:
        description: 'Workflow run ID to rollback to (fetched by going to the "Deploy Website" workflow and looking at the url)'
        required: true
        type: string

jobs:
  # Call the deploy workflow with rollback parameters
  rollback:
    uses: ./.github/workflows/deploy_website.yml
    with:
      is_rollback: true
      artifact_date: ${{ inputs.artifact_date }}
      run_id: ${{ inputs.run_id }}
